language: ruby
dist: trusty
sudo: false
rvm:
- 2.3.3
script: bundle exec rake
before_install:
- gem update bundler
notifications:
  email:
    recipients:
    - pmcevoy@logit.io
    on_success: change
    on_failure: change
deploy:
  provider: rubygems
  api_key:
    secure: SCMxiWuAWdKdmEGhcbnDP/GEd55tvUdcHVCDzdz7KfdYi3oe5OQTh3uvv4EmNX7T7SSnZtM7+ftK7b7ENBNy3SQk4k7ucn5yq1PPeUuqnCc7ih4LunjfQj6IzyGMwZN5SbhvlIcCSlwlo8ciezarkx12v4o0Gyv25+D/gthQ/VQafbr/WnavPXOOc7u36tpanm+S+P0ixzTzDtiTn2vodRJwy16LV/cnoX4N4pilOkKx8PJPGlCQspBfvPH4UUqD1jNrZqYp6Wy44D72fuqLWREg3xgxGz0gh4buLwAtg2FALcMA7s3E7PMWaFiYWbGl48PGyCBGIoQyLIYB6cU2uXYlkyADELLwiu1gqCnE5WV0ZYFnNqVuvvuJgXnmKNEP+s6HURZqYlkuJhDjD86TA/wTBYLp9G2tb1ubmYF/t7NkSY41jfR2QZAOpbgZWfsCyEpBKFbpXif1skF8k8OoK2i4BPyaqNq9Y0C53o83hZKwH1YzVTkY9hBbP32i0n42QxlKsTdtolK7Tn5PulV+BIWGMCz79KDcKSETlndhtvCHeKx25V1JQ2aO1MxBiq4Rsq8J7joFyvXlAUSFZUYW0yI/1FpA33JT8IVkCrhVS5MUPRpz/NdLBUWjjOmYmLaBbOXEo9wm7BfKYCpdp5W9pxqYWmPTNZx66h4Bg6NXPO4=
  gem: fluent-plugin-logit
  on:
    repo: logit-io/fluent-plugin-logit
